config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'

  authenticate :user do
  	resources :quizzs
  	resources :types
  	resources :questions
  	resources :tags
  	resources :answers
  end
  resources :answers, except: [:update, :destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, Quizz
        can [:read,:create], Answer
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :choice
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :tag
  has_many :answers
  
  accepts_nested_attributes_for :answers
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quizz
  has_many :answers, dependent: :destroy
  has_many :choices, dependent: :destroy

  accepts_nested_attributes_for :choices, reject_if: :all_blank, allow_destroy: true
end

app/models/quizz.rb
class Quizz < ApplicationRecord
  belongs_to :type
  has_many :questions
  has_many :tags

  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :choices
	belongs_to :quizz	
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :quizzs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :answers, dependent: :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@quizzs = Quizz.all
  end
end

app/controllers/quizzs_controller.rb
class QuizzsController < ApplicationController
  before_action :set_quizz, only: [:show, :edit, :update, :destroy]

  # GET /quizzs
  # GET /quizzs.json
  def index
    @quizzs = Quizz.all
  end

  # GET /quizzs/1
  # GET /quizzs/1.json
  def show
  end

  # GET /quizzs/new
  def new
    @quizz = Quizz.new
    @types = Type.all
  end

  # GET /quizzs/1/edit
  def edit
    @types = Type.all
  end

  # POST /quizzs
  # POST /quizzs.json
  def create
    @quizz = Quizz.new(quizz_params)

    respond_to do |format|
      if @quizz.save
        format.html { redirect_to @quizz, notice: 'Quizz was successfully created.' }
        format.json { render :show, status: :created, location: @quizz }
      else
        format.html { render :new }
        format.json { render json: @quizz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzs/1
  # PATCH/PUT /quizzs/1.json
  def update
    respond_to do |format|
      if @quizz.update(quizz_params)
        format.html { redirect_to @quizz, notice: 'Quizz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quizz }
      else
        format.html { render :edit }
        format.json { render json: @quizz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzs/1
  # DELETE /quizzs/1.json
  def destroy
    @quizz.destroy
    respond_to do |format|
      format.html { redirect_to quizzs_url, notice: 'Quizz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quizz
      @quizz = Quizz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quizz_params
      params.require(:quizz).permit(:description, :type_id, :image,
        tags_attributes: [:id,:description,:_destroy])
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:id, :description)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:description,:image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="row d-flex justify-content">
	<% @quizzs.each do |quizz| %>
	<div class="card m-3" style="width: 18rem; height:  18rem">
		<h3><span class="text-left badge badge-secondary">
			<%= quizz.type.description %></span></h3>
		<div class="card-body text-center">
			<div style="height: 10rem">
				<h1 class="card-title"> <%= quizz.image %> </h1>
				<p class="card-text"> <%= quizz.description %></p>
			</div>			
			<div>
				<%= link_to 'Responder', new_answer_path({:quizz_id => quizz.id}), class: "btn btn-info" %>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <%= form.label :description %>
        <%= form.text_field :description, :class=>'form-control col-md-12'%>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        Emoji
        <%= form.text_field :image, :class=>'form-control col-md-12'%>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="actions col-md-6 text-right">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/types/edit.html.erb
	<div class="container">
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6">
				<h1>Editing Type</h1>
			</div>
		</div>
	</div>				

	<%= render 'form', type: @type %>

	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6 text-right">
				<%= link_to 'Back', types_path %>
			</div>
		</div>
	</div>
</div>				

app/views/types/index.html.erb
  <p id="notice"><%= notice %></p>

<h1>Types</h1>
<p class="text-right"><%= link_to 'New Type', new_type_path %></p>

<table class="table table-borderless">
 <thead>
    <tr>
      <th>Description</th>
      <th>Emoji</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td scope="col"><%= type.description %></td>
        <td scope="col"><%= type.image %></td>
        <td scope="col">
          <%= link_to 'Edit', edit_type_path(type) %> |
          <%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/types/new.html.erb
<div>
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6">
				<h1>New Type</h1>
			</div>
		</div>
	</div>

	<%= render 'form', type: @type %>

	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6 text-right">
				<%= link_to 'Back', types_path %>
			</div>
		</div>
	</div>				
</div>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><span class="text-muted">Type: </span><%= @type.description %></h1>
</p>
<p>
  <strong>Emoji:</strong>
  <%= @type.image %>
</p>

<p class="text-right">
	<%= link_to 'Back', types_path %>
</p>