config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'

  authenticate :user do
  	resources :quizzs
  	resources :types
  	resources :questions
  	resources :tags
  	resources :answers
  end
  resources :answers, except: [:update, :destroy]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :choice
  belongs_to :question
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]


  # GET /questions
  # GET /questions.json
  def index
    @answers = Answer.all
  end

  # GET /answer/1
  # GET /answer/1.json
  def show
    @quizz = @answer.question.quizz
    @answers = Quizz.joins(
      'JOIN questions ON questions.quizz_id = quizzs.id
       JOIN answers ON answers.question_id = questions.id
       JOIN choices ON answers.choice_id = choices.id'
      ).where('user_id= ? and quizz_id = ?',current_user.id,@quizz.id).uniq

    @map = Hash.new

    @answers[0].questions.each do |question|
      @choice = question.answers[0].choice

      if @map[@choice.tag.id].nil?
       @map[@choice.tag.id] = 0
      end
      @map[@choice.tag.id] = @map[@choice.tag.id] + 1   
    end

    aux = 0 
    @tag_id = 0
    @map.each do |key,value|
      if value > aux
        @tag_id = key
      end
    end

    @tagresult = Tag.find(@tag_id)
  end

  # GET /answer/new
  def new
    @user_id = current_user
    @quizz_id = params[:quizz_id]
    @quizz = Quizz.find(params[:quizz_id])
    @answer = Answer.new
  end

  # POST /answer
  # POST /answer.json
  def create

         quizz_id = answer_params[:quizz_id]  
                       
          def save_answers         
            answer_params[:questions].each do |key,value|
              question_id = key.to_i
              choice_id = value.to_i            
              @answer = Answer.new(:question_id => question_id, :choice_id => choice_id, :user_id => current_user.id)
              if !@answer.save 
                return false
              end              
            end
            return true
          end

          respond_to do |format|
              if save_answers() == true 
                  format.html { redirect_to @answer, notice: 'Resposta salva com sucesso.' }
                  format.json { render :show, status: :created, location: @answer } 
              else
                  format.html { redirect_to new_answer_path({:quizz_id => quizz_id})}
                  format.json { render json: @answer.errors, status: :unprocessable_entity }
              end
          end              
  end

  # PATCH/PUT /answer/1
  # PATCH/PUT /answer/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Sua resposta foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answer/1
  # DELETE /answer/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answer_url, notice: 'A resposta foi excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:quizz_id,:questions => {})
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :quizz_id, :type=>'hidden', :value=>@quizz_id %>

  <div class="field">
      <h2><%= @quizz.description %></h2>
  </div>

  <% @quizz.questions.each do |question|%>     
          <br> 
          <h3><%= question.description =%></h3>

             <fieldset id="answer[questions[<%= question.id %>]">
                <% question.choices.each do |choice| %>
                  <p> 
                    <input type="radio" name="answer[questions[<%= question.id %>]]" value="<%= choice.id %>">
                    <%= choice.description %> 
                  </p>
                <% end %>
            </fieldset> 
    <% end %>
  
  <div class="actions">
    <%= form.submit 'Enviar'%>
  </div>

  <br>
<% end %>

app/views/answers/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Respostas</h1>

  <table class="table table-sm table-borderless">
    <thead>
      <tr>
        <th></th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @answers.each do |answer| %>
        <tr>
          <td><%= answer.quizz.description %></td>
          <td><%= answer.question.description %></td>
          <td><%= answer.choice.description %></td>
          <td><%= link_to 'Visualizar', answer %></td>
          <td><%= link_to 'Editar', edit_answer_path(answer) %></td>
          <td><%= link_to 'Responder', new_answer_path({:question_id => question}) %> </td>
          <td><%= link_to 'Excluir', answer, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/answers/new.html.erb
<div class="container">
	<h1 class="text-muted">🕹 Responda o Quizz </h1>
	<br>
	<%= render 'form', answer: @answer %>

	<%= link_to 'Voltar', root_path %>
</div>

app/views/answers/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<div class="col-md-12">

		<h1><span class="text-muted">Quizz: </span><%= @quizz.description %></h1>
		
		<br>

		<div class="row">
			<div class="col-md-6">
				<h2>Suas Respostas </h2>

				<br>
				
				<div class="row">
					<% @map = Hash.new %>
					<% @answers.each do |answer| %>
						<% @total = answer.questions.count %>
						<% answer.questions.each do |question| %>
							
							<div class="col-md-12">
								<div class="row">
									<div class="col-md-12">
										<strong><%= question.description %>: </strong>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<% @choice = question.answers[0].choice %>
										<%= @choice.description %>
									</div>
								</div>
							</div>
						<% end %>
					<% end %>
				</div>
			</div>

			<div class="col-md-6">
				<div class="row">
					<div class="col-md-12">
						<h2>Resultado</h2>
						<%= @tagresult.description %>
					</div>
				</div>
			</div>			
			
			<p class="col-md-12 text-right">
				<%= link_to 'Voltar', new_answer_path({:quizz_id => @quizz.id}) %>
			</p>
		</div>
	</div>