config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'

  authenticate :user do
  	resources :quizzs
  	resources :types
  	resources :questions
  	resources :tags
  	resources :answers
  end
  resources :answers, except: [:update, :destroy]
end

app/models/quizz.rb
class Quizz < ApplicationRecord
  belongs_to :type
  has_many :questions
  has_many :tags

  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
end

app/controllers/quizzs_controller.rb
class QuizzsController < ApplicationController
  before_action :set_quizz, only: [:show, :edit, :update, :destroy]

  # GET /quizzs
  # GET /quizzs.json
  def index
    @quizzs = Quizz.all
  end

  # GET /quizzs/1
  # GET /quizzs/1.json
  def show
  end

  # GET /quizzs/new
  def new
    @quizz = Quizz.new
    @types = Type.all
  end

  # GET /quizzs/1/edit
  def edit
    @types = Type.all
  end

  # POST /quizzs
  # POST /quizzs.json
  def create
    @quizz = Quizz.new(quizz_params)

    respond_to do |format|
      if @quizz.save
        format.html { redirect_to @quizz, notice: 'Quizz was successfully created.' }
        format.json { render :show, status: :created, location: @quizz }
      else
        format.html { render :new }
        format.json { render json: @quizz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzs/1
  # PATCH/PUT /quizzs/1.json
  def update
    respond_to do |format|
      if @quizz.update(quizz_params)
        format.html { redirect_to @quizz, notice: 'Quizz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quizz }
      else
        format.html { render :edit }
        format.json { render json: @quizz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzs/1
  # DELETE /quizzs/1.json
  def destroy
    @quizz.destroy
    respond_to do |format|
      format.html { redirect_to quizzs_url, notice: 'Quizz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quizz
      @quizz = Quizz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quizz_params
      params.require(:quizz).permit(:description, :type_id, :image,
        tags_attributes: [:id,:description,:_destroy])
    end

end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/views/quizzs/_form.html.erb
<%= form_with(model: quizz, local: true) do |form| %>
  <% if quizz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quizz.errors.count, "error") %> prohibited this quizz from being saved:</h2>

      <ul>
      <% quizz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-12">
    <div class="row"> 
      <div class="col-md-6">
        <%= form.label :description %>
        <%= form.text_field :description, :class=>'form-control col-md-12' %>
      </div>
    </div>

    <div class="row"> 
      <div class="col-md-6">
        Emoji
        <%= form.text_field :image, :class=>'form-control col-md-12'%>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <%= form.label :type_id %>
        <%= collection_select(:quizz,:type_id, @types, :id, :description,{}, {:class=>'form-control col-md-12'}) %>
      </div>
    </div>

     <div class="row">
      <div class="col-md-12" id="tags">
        <br>  
        <h3>Tags</h3>
        <%= form.fields_for :tags do |tag_fields| %>
          <%= render partial: "tag_fields", locals: {f: tag_fields} %>
        <% end %>
        <p><%= link_to_add_association('Add tag',form, :tags) %></p>
      </div>
    </div>
    
    <div class="row">
      <div class="actions col-md-6 text-right">
        <%= form.submit %>
      </div>
    </div>
  </div>
</div>
<% end %> 

app/views/quizzs/_tag_fields.html.erb
<div class="nested-fields row">
	<div class="field col-md-5">
  	  <%= f.text_field :description, :class=>'form-control col-md-12' %>
  	</div>
  	<div class="col-md-1">
  		<%= link_to_remove_association('Remover',f) %>
  	</div>
</div>

app/views/quizzs/edit.html.erb
<div class="container">
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6">
				<h1>Editing Quizz</h1>
			</div>
		</div>
	</div>

	<%= render 'form', quizz: @quizz %>
	
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6 text-right">
				<%= link_to 'Show', @quizz %> |
				<%= link_to 'Back', quizzs_path %>
			</div>
		</div>
	</div>
</div>

app/views/quizzs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>
<p class="text-right"><%= link_to 'New Quizz', new_quizz_path %></p>  

<table class="table table-borderless">
  <thead>
    <tr>
      <th>Description</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzs.each do |quizz| %>
      <tr>
        <td scope="col"><%= quizz.description %></td>
        <td scope="col"><%= quizz.type.description %></td>
        <td scope="col">
          <%= link_to 'Show', quizz %> |
          <%= link_to 'Edit', edit_quizz_path(quizz) %> |
        <%= link_to 'Destroy', quizz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/quizzs/new.html.erb
<div>
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6">
				<h1>New Quizz</h1>
			</div>
		</div>
	</div>				

	<%= render 'form', quizz: @quizz %>	

	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6 text-right">
				<%= link_to 'Back', quizzs_path %>
			</div>
		</div>
	</div>				
</div>

app/views/quizzs/show.html.erb
<p id="notice"><%= notice %></p>


<h1><span class="text-muted">Quizz: </span><%= @quizz.description %> <%= @quizz.image %></h1>
<br>

<p>
  <strong>Type:</strong>
  <%= @quizz.type.description %>
</p>

<p>
  <strong>Tags:</strong>
	<% @quizz.tags.each do |tag| %>
		<span class="badge badge-primary"><%= tag.description %></span>
	<% end %>
</p>	

<div class="text-right">
  <td><%= link_to 'New question', new_question_path(:quizzid => @quizz.id) %></td>
</div>

<% if @quizz.questions.size > 0 %>

	<h2>Questions</h2>
	
	<% contador = 0 %>
	<table class="table">	
		<thead></thead>
		<tbody>
			<% @quizz.questions.each do |question| %>
				<tr>
					<td><%=	contador = contador+1 %></td>
					<td><%= question.description %></td>
					<td><%= link_to 'Edit', edit_question_path(question, :quizzid => @quizz.id) %></td>
					<td><%= link_to 'Show', question %></td>		
					<td><%= link_to 'Delete', question, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
				</tr>
			<% end %>
		</tbody>	
	</table>	
<% end %>

<p class="text-right">
	<%= link_to 'Back', quizzs_path %>
</p>